<a href="https://colab.research.google.com/github/subhobrata/deeplizard/blob/master/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [110]:
print(torch.__version__)

1.0.1.post2


In [111]:
torch.cuda.is_available()

True

In [112]:
torch.version.cuda

'10.0.130'

In [113]:
t = torch.tensor([1,2,3])
t

tensor([1, 2, 3])

In [114]:
t = t.cuda()
t

tensor([1, 2, 3], device='cuda:0')

In [115]:
a = [1,2,3,4]
a

[1, 2, 3, 4]

In [116]:
type(a)

list

In [117]:
print(type(a))

<class 'list'>


In [118]:
a[2]

3

In [0]:
dd = [
[1,2,3],
[4,5,6],
[7,8,9]
]

In [120]:
dd[0][2]

3

In [121]:
dd[0]

[1, 2, 3]

In [122]:
dd[1]

[4, 5, 6]

In [123]:
dd[2]

[7, 8, 9]

In [124]:
dd[0][1]

2

In [125]:
dd[0][0]

1

In [126]:
dd[2][0]

7

In [127]:
t = torch.tensor(dd)
t


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [128]:
type(t)

torch.Tensor

In [129]:
t.shape

torch.Size([3, 3])

In [130]:
t.reshape(1,9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [131]:
t.reshape(1,9).shape

torch.Size([1, 9])

In [0]:
import torch
import numpy as np

In [0]:
data = np.array([1,2,3])


In [0]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [135]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [136]:
print(t1.dtype)
print(t2.dtype)
print(t3.dtype)
print(t4.dtype)

torch.float32
torch.int64
torch.int64
torch.int64


In [137]:
torch.get_default_dtype()

torch.float32

In [138]:
torch.tensor(np.array([1,2,3]))

tensor([1, 2, 3])

In [139]:
torch.tensor(np.array([1.,2.,3.]))

tensor([1., 2., 3.], dtype=torch.float64)

In [140]:
torch.tensor(np.array([1,2,3]),dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [141]:
data = np.array([1,2,3])
data

array([1, 2, 3])

In [0]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [0]:
data[0]=0
data[1]=0
data[2]=0


In [144]:
print(t1)
print(t2)

tensor([1., 2., 3.])
tensor([1, 2, 3])


In [145]:
print(t3)
print(t4)

tensor([0, 0, 0])
tensor([0, 0, 0])


In [0]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
],dtype=torch.float32)

In [147]:
t.size()

torch.Size([3, 4])

In [148]:
t.shape

torch.Size([3, 4])

In [149]:
#rank of a Tensor
len(t.shape)

2

In [150]:
torch.tensor(t.shape).prod()

tensor(12)

In [151]:
t.numel()

12

In [152]:
t.reshape(4,3)

tensor([[1., 1., 1.],
        [1., 2., 2.],
        [2., 2., 3.],
        [3., 3., 3.]])

In [153]:
t.reshape(6,2)

tensor([[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.],
        [3., 3.],
        [3., 3.]])

In [154]:
t.reshape(12,1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])

In [155]:
print(t.reshape(1,12))
print(t.reshape(1,12).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [156]:
print(t.reshape(1,12).squeeze())
print(t.reshape(1,12).squeeze().shape)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])


In [157]:
print(t.reshape(1,12).squeeze().unsqueeze(dim=0))
print(t.reshape(1,12).squeeze().unsqueeze(dim=0).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [0]:
def flatten(t):
  t = t.reshape(1,-1)
  t = t.squeeze()
  return t

In [159]:
flatten(t)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [160]:
flatten(t).shape

torch.Size([12])

In [161]:
t.reshape(1,12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [162]:
t.reshape(1,12).shape

torch.Size([1, 12])

In [163]:
print(t.reshape(4,3).squeeze())
print(t.reshape(4,3).squeeze().shape)

tensor([[1., 1., 1.],
        [1., 2., 2.],
        [2., 2., 3.],
        [3., 3., 3.]])
torch.Size([4, 3])


In [164]:
print(t.reshape(4,3).squeeze().unsqueeze(dim=0))
print(t.reshape(4,3).squeeze().unsqueeze(dim=0).shape)

tensor([[[1., 1., 1.],
         [1., 2., 2.],
         [2., 2., 3.],
         [3., 3., 3.]]])
torch.Size([1, 4, 3])


In [165]:
print(t.reshape(4,3).squeeze().unsqueeze(dim=1))
print(t.reshape(4,3).squeeze().unsqueeze(dim=1).shape)

tensor([[[1., 1., 1.]],

        [[1., 2., 2.]],

        [[2., 2., 3.]],

        [[3., 3., 3.]]])
torch.Size([4, 1, 3])


In [166]:
print(t.reshape(4,3).squeeze().unsqueeze(dim=2))
print(t.reshape(4,3).squeeze().unsqueeze(dim=2).shape)

tensor([[[1.],
         [1.],
         [1.]],

        [[1.],
         [2.],
         [2.]],

        [[2.],
         [2.],
         [3.]],

        [[3.],
         [3.],
         [3.]]])
torch.Size([4, 3, 1])


In [0]:
t1 = torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])

In [0]:
t2 = torch.tensor([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2]
])

In [0]:
t3 = torch.tensor([
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3]
])

In [0]:
t = torch.stack((t1,t2,t3))

In [171]:
t

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])

In [172]:
t.shape

torch.Size([3, 4, 4])

In [173]:
t = t.reshape(3,1,4,4)
t

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])

In [174]:
t[0]

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])

In [175]:
t[0][0]

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [176]:
t[0][0][0]

tensor([1, 1, 1, 1])

In [177]:
t[0][0][0][0]

tensor(1)

In [178]:
t.reshape(1,-1)[0]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [179]:
t.reshape(-1)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [180]:
t.view(t.numel())

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [181]:
t.flatten()

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [0]:
import torch
import numpy as np

In [0]:
t1 = torch.tensor([
    [1,2],
    [3,4]
],dtype=torch.float32)

In [0]:
t2 = torch.tensor([
    [9,8],
    [7,6]
],dtype=torch.float32)

In [185]:
t1[0][0]

tensor(1.)

In [186]:
t2[0][0]

tensor(9.)

In [187]:
t1+t2

tensor([[10., 10.],
        [10., 10.]])

In [188]:
t1+2

tensor([[3., 4.],
        [5., 6.]])

In [189]:
t1-2

tensor([[-1.,  0.],
        [ 1.,  2.]])

In [190]:
t1*2

tensor([[2., 4.],
        [6., 8.]])

In [191]:
t1/2

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [192]:
t1.add(2)

tensor([[3., 4.],
        [5., 6.]])

In [193]:
t1.sub(2)

tensor([[-1.,  0.],
        [ 1.,  2.]])

In [194]:
t1.mul(2)

tensor([[2., 4.],
        [6., 8.]])

In [195]:
t1.div(2)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [197]:
np.broadcast_to(2,t1.shape)

array([[2, 2],
       [2, 2]])

In [198]:
t1

tensor([[1., 2.],
        [3., 4.]])

In [199]:
t1+2

tensor([[3., 4.],
        [5., 6.]])

In [200]:
t1+torch.tensor(
    np.broadcast_to(2,t1.shape)
    ,dtype=torch.float32)

tensor([[3., 4.],
        [5., 6.]])

In [0]:
t1 = torch.tensor([
    [1,1],
    [1,1]
],dtype=torch.float32)

t2 = torch.tensor([2,4],dtype=torch.float32)

In [202]:
t1.shape

torch.Size([2, 2])

In [203]:
t2.shape

torch.Size([2])

In [204]:
np.broadcast_to(t2.numpy(),t1.shape)

array([[2., 4.],
       [2., 4.]], dtype=float32)

In [205]:
t1+t2

tensor([[3., 5.],
        [3., 5.]])

In [0]:
t = torch.tensor([
    [0,5,0],
    [6,0,7],
    [0,8,0]
], dtype=torch.float32)

In [208]:
t.eq(0)


tensor([[1, 0, 1],
        [0, 1, 0],
        [1, 0, 1]], dtype=torch.uint8)

In [209]:
t.ge(0)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.uint8)

In [210]:
t.gt(0)

tensor([[0, 1, 0],
        [1, 0, 1],
        [0, 1, 0]], dtype=torch.uint8)

In [211]:
t.lt(0)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.uint8)

In [212]:
t.le(7)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 0, 1]], dtype=torch.uint8)

In [213]:
t <= torch.tensor(
    np.broadcast_to(7, t.shape)
    ,dtype=torch.float32
)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 0, 1]], dtype=torch.uint8)

In [0]:
t = torch.tensor([
    [0,1,0],
    [2,0,2],
    [0,3,0]
], dtype=torch.float32)

In [215]:
t.sum()

tensor(8.)

In [216]:
t.numel()

9

In [217]:
t.sum().numel()

1

In [218]:
t.sum().numel()<t.numel()

True

In [219]:
t.prod()

tensor(0.)

In [220]:
t.mean()

tensor(0.8889)

In [221]:
t.std()

tensor(1.1667)

In [0]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

In [223]:
t.sum(dim=0)

tensor([6., 6., 6., 6.])

In [224]:
t.sum(dim=1)

tensor([ 4.,  8., 12.])

In [225]:
t[0]

tensor([1., 1., 1., 1.])

In [226]:
t[1]

tensor([2., 2., 2., 2.])

In [227]:
t[2]

tensor([3., 3., 3., 3.])

In [228]:
t[0]+t[1]+t[2]

tensor([6., 6., 6., 6.])

In [229]:
t[0].sum()

tensor(4.)

In [230]:
t[1].sum()

tensor(8.)

In [231]:
t

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [232]:
t[2].sum()

tensor(12.)

In [233]:
t.sum(dim=1)

tensor([ 4.,  8., 12.])

In [234]:
t.sum(dim=0)

tensor([6., 6., 6., 6.])

In [0]:
t = torch.tensor([
    [1,0,0,2],
    [0,3,3,0],
    [4,0,0,5]
], dtype=torch.float32)

In [237]:
t.max()

tensor(5.)

In [238]:
t.argmax()

tensor(11)

In [239]:
t.flatten()

tensor([1., 0., 0., 2., 0., 3., 3., 0., 4., 0., 0., 5.])

In [240]:
t.max(dim=0)

(tensor([4., 3., 3., 5.]), tensor([2, 1, 1, 2]))

In [241]:
t.argmax(dim=0)

tensor([2, 1, 1, 2])

In [242]:
t.max(dim=1)

(tensor([2., 3., 5.]), tensor([3, 2, 3]))

In [243]:
t.argmax(dim=1)

tensor([3, 2, 3])

In [0]:
t = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
], dtype=torch.float32)

In [245]:
t.mean()

tensor(5.)

In [246]:
t.mean().item()

5.0

In [247]:
t.mean(dim=0).tolist()

[4.0, 5.0, 6.0]

In [249]:
t.mean(dim=1).tolist()

[2.0, 5.0, 8.0]

In [250]:
t.mean(dim=0).numpy()

array([4., 5., 6.], dtype=float32)

In [248]:
t

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])