<a href="https://colab.research.google.com/github/subhobrata/deeplizard/blob/master/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [2]:
print(torch.__version__)

1.0.1.post2


In [3]:
torch.cuda.is_available()

True

In [4]:
torch.version.cuda

'10.0.130'

In [5]:
t = torch.tensor([1,2,3])
t

tensor([1, 2, 3])

In [7]:
t = t.cuda()
t

tensor([1, 2, 3], device='cuda:0')

In [8]:
a = [1,2,3,4]
a

[1, 2, 3, 4]

In [9]:
type(a)

list

In [10]:
print(type(a))

<class 'list'>


In [11]:
a[2]

3

In [0]:
dd = [
[1,2,3],
[4,5,6],
[7,8,9]
]

In [13]:
dd[0][2]

3

In [14]:
dd[0]

[1, 2, 3]

In [15]:
dd[1]

[4, 5, 6]

In [16]:
dd[2]

[7, 8, 9]

In [17]:
dd[0][1]

2

In [18]:
dd[0][0]

1

In [19]:
dd[2][0]

7

In [20]:
t = torch.tensor(dd)
t


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [21]:
type(t)

torch.Tensor

In [22]:
t.shape

torch.Size([3, 3])

In [23]:
t.reshape(1,9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [24]:
t.reshape(1,9).shape

torch.Size([1, 9])